# -*- coding: utf-8 -*-
"""Fake_News_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uaQIuzie3nnOSHVCfKRDRHyg8xJN2wD1
"""

import os
print(os.listdir())

import pandas as pd

fake = pd.read_csv("Fake.csv", engine='python', on_bad_lines='skip')
true = pd.read_csv("True.csv", engine='python', on_bad_lines='skip')

print(fake.shape, true.shape)

# Add labels
fake["label"] = 0
true["label"] = 1

# Take equal samples (IMPORTANT FIX)
fake = fake.sample(n=10000, random_state=42)
true = true.sample(n=10000, random_state=42)

# Combine
data = pd.concat([fake, true])
data = data.sample(frac=1, random_state=42)

print("Balanced dataset:", data.shape)

X = data["text"]
y = data["label"]

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    stop_words="english",
    max_features=5000   # IMPORTANT (prevents bias)
)

X = vectorizer.fit_transform(X)

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

print("Model trained ✅")

from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

def predict_news(news):
    vector = vectorizer.transform([news])
    pred = model.predict(vector)
    return "REAL" if pred[0] == 1 else "FAKE"

print(predict_news("Government announces new economic policy"))
print(predict_news("Aliens discovered living under ocean in India"))

import matplotlib.pyplot as plt

plt.bar(["Accuracy", "Error"], [accuracy, 1 - accuracy])
plt.title("Model Performance")
plt.show()

print(predict_news("Government announces new economic policy"))
print(predict_news("Aliens discovered living under ocean in India"))
print(predict_news("Breaking: Scientists develop new vaccine for cancer treatment"))